# Generated by Django 3.0.6 on 2020-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StProformaCabeceraTmp',
            fields=[
                ('cod_comprobante', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=2)),
                ('empresa', models.IntegerField()),
                ('cod_agencia', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cod_forma_pago', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_tipo_identificacion', models.IntegerField(blank=True, null=True)),
                ('cod_persona', models.CharField(blank=True, max_length=14, null=True)),
                ('nombre_persona', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_tipo_identificacion_gar', models.IntegerField(blank=True, null=True)),
                ('cod_persona_gar', models.CharField(blank=True, max_length=14, null=True)),
                ('nombre_persona_gar', models.CharField(blank=True, max_length=50, null=True)),
                ('num_cuotas', models.IntegerField(blank=True, null=True)),
                ('base_imponible', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_exenta', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('financiamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cod_bodega_egreso', models.IntegerField(blank=True, null=True)),
                ('cod_politica', models.IntegerField(blank=True, null=True)),
                ('fecha_vencimiento1', models.DateField(blank=True, null=True)),
                ('por_interes', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('apellido_persona', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_persona_gar', models.CharField(blank=True, max_length=50, null=True)),
                ('entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'st_proforma_cabecera_tmp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StProformaDetalleTmp',
            fields=[
                ('cod_comprobante', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=2)),
                ('empresa', models.IntegerField()),
                ('secuencia', models.IntegerField()),
                ('cod_producto', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=200, null=True)),
                ('es_serie', models.BooleanField(blank=True, null=True)),
                ('cod_estado_producto', models.CharField(blank=True, max_length=2, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('iva', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'st_proforma_detalle_tmp',
                'managed': False,
            },
        ),
    ]
