# Generated by Django 3.0.6 on 2020-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_stclientesimagenesdocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtImagenProforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.FloatField(blank=True, null=True)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_comprobante', models.CharField(max_length=9)),
                ('cod_agencia', models.IntegerField()),
                ('agencia', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cod_persona', models.CharField(max_length=14)),
                ('doc_sol', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tiene_doc', models.CharField(blank=True, max_length=1, null=True)),
                ('doc_img', models.IntegerField(blank=True, null=True)),
                ('path_dir', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_transaccion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VT_IMAGEN_PROFORMA',
                'managed': False,
            },
        ),
    ]
