# Generated by Django 3.0.6 on 2020-10-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_vtimagenproforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgTmp',
            fields=[
                ('empresa', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prueba')),
                ('nombre', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'img_tmp',
                'managed': False,
            },
        ),
    ]
