# Generated by Django 3.0.6 on 2020-10-24 21:19

import core.facturacion.modelos.comprobante.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_imgtmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StImagenesPagare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.FloatField()),
                ('tipo_comprobante', models.CharField(max_length=2)),
                ('cod_comprobante', models.CharField(max_length=15)),
                ('cod_tipo_documento', models.FloatField()),
                ('path_img', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/', location='\\\\10.10.10.66\\imagenes'), upload_to=core.facturacion.modelos.comprobante.models.get_upload_path)),
                ('fecha_adicion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ST_IMAGENES_PAGARE',
                'managed': False,
            },
        ),
    ]
