# Generated by Django 3.0.6 on 2020-10-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_stimagenespagare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgTmp',
        ),
    ]
