# Generated by Django 3.0.6 on 2020-10-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_delete_imgtmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtComprobante',
            fields=[
                ('empresa', models.IntegerField()),
                ('tipo_comprobante', models.CharField(max_length=2)),
                ('cod_comprobante', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cod_agencia', models.IntegerField()),
                ('nom_agencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='agencia')),
                ('fecha', models.DateField()),
                ('forma_pago', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_agente', models.CharField(blank=True, max_length=14, null=True)),
                ('nom_agente', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_persona', models.CharField(max_length=14)),
                ('nom_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('anulado', models.CharField(blank=True, max_length=1, null=True)),
                ('cod_liquidacion', models.CharField(max_length=9)),
                ('numero_pagos', models.IntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('useridc', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_politica', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=62, null=True)),
                ('verificador', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vt_comprobante',
                'managed': False,
            },
        ),
    ]
