# Generated by Django 3.0.6 on 2020-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_vtcomprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtProforma',
            fields=[
                ('empresa', models.IntegerField()),
                ('tipo_comprobante', models.CharField(max_length=2)),
                ('cod_comprobante', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('comprobante_manual', models.CharField(max_length=9)),
                ('cod_agencia', models.IntegerField()),
                ('nom_agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('cod_forma_pago', models.CharField(max_length=3)),
                ('cod_persona_age', models.CharField(max_length=14)),
                ('nom_agente', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_persona', models.CharField(max_length=14)),
                ('nom_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('es_invalido', models.BooleanField()),
                ('es_anulado', models.BooleanField()),
                ('es_aprobado', models.BooleanField()),
                ('es_facturado', models.BooleanField()),
                ('cantidad_mov', models.IntegerField()),
                ('cantidad_mov_completo', models.IntegerField()),
                ('fecha_sol_ver_telefonica', models.DateField(blank=True, null=True)),
                ('fecha_ver_telefonica', models.DateField(blank=True, null=True)),
                ('fecha_sol_ver_campo', models.DateField(blank=True, null=True)),
                ('fecha_ver_campo', models.DateField(blank=True, null=True)),
                ('fecha_negacion', models.DateField(blank=True, null=True)),
                ('es_verificado', models.BooleanField(blank=True, null=True)),
                ('es_detenido', models.BooleanField(blank=True, null=True)),
                ('tipo_sol_amiga', models.BooleanField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('cod_parametro', models.IntegerField(blank=True, null=True)),
                ('es_preaprobado', models.IntegerField(blank=True, null=True)),
                ('puntaje_acierta', models.IntegerField(blank=True, null=True)),
                ('es_envio_supervisor', models.BooleanField(blank=True, null=True)),
                ('cat_credireport', models.CharField(blank=True, max_length=4000, null=True)),
                ('cod_cat_cliente', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'vt_PROFORMA',
                'managed': False,
            },
        ),
    ]
