# Generated by Django 3.0.6 on 2020-11-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_vtproforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtVentaMotor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('cod_comprobante', models.CharField(max_length=9)),
                ('cod_agencia', models.IntegerField()),
                ('agencia', models.CharField(max_length=50)),
                ('cod_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_producto', models.CharField(max_length=40)),
                ('numero_serie', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=20)),
                ('camvcpn', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.IntegerField()),
                ('origen', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=30, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=13, null=True)),
                ('fecha_venta', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('email', models.CharField(blank=True, max_length=4000, null=True)),
                ('cod_persona', models.CharField(max_length=14)),
                ('nombre_persona', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono1h', models.CharField(blank=True, max_length=15, null=True)),
                ('e_mailh', models.CharField(blank=True, max_length=60, null=True)),
                ('venta', models.CharField(blank=True, max_length=19, null=True)),
            ],
            options={
                'db_table': 'vt_venta_motor1',
                'managed': False,
            },
        ),
    ]
