# Generated by Django 3.1.5 on 2021-01-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_vtventamotor1'),
    ]

    operations = [
        migrations.CreateModel(
            name='StComprobanteElectronico',
            fields=[
                ('empresa', models.IntegerField()),
                ('tipo_comprobante', models.CharField(max_length=50)),
                ('cod_comprobante', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nro_autorizacion', models.CharField(blank=True, max_length=49, null=True)),
                ('nro_serie', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_validez', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('autoimpresion', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo_comprobante_alt', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_comprobante_alt', models.CharField(blank=True, max_length=9, null=True)),
                ('secuencia', models.IntegerField(blank=True, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=14, null=True)),
                ('comprobante_sri', models.CharField(blank=True, max_length=20, null=True)),
                ('archivo_xml', models.CharField(blank=True, max_length=4000, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('direccion_matriz', models.CharField(blank=True, max_length=200, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=250, null=True)),
                ('archivo_xml_anulado', models.CharField(blank=True, max_length=4000, null=True)),
                ('cod_tipo_contribuyente', models.IntegerField(blank=True, null=True)),
                ('fecha_tipo_cont', models.DateField(blank=True, null=True)),
                ('direccion_cliente', models.CharField(blank=True, max_length=300, null=True)),
                ('leyenda_tipo_cont', models.CharField(blank=True, max_length=50, null=True)),
                ('xml_electronico', models.TextField(blank=True, null=True)),
                ('xml_pruebas', models.TextField(blank=True, null=True)),
                ('clave_acceso', models.CharField(blank=True, max_length=64, null=True)),
                ('clave_pruebas', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'ST_COMPROBANTE_ELECTRONICO',
                'managed': False,
            },
        ),
    ]
