# Generated by Django 3.0.6 on 2020-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(db_column='tipoDoc', max_length=255)),
                ('fechaemision', models.DateField(db_column='fechaEmision')),
                ('fechaautorizacion', models.DateTimeField(db_column='fechaAutorizacion')),
                ('nodocumento', models.CharField(db_column='noDocumento', max_length=255)),
                ('claveacceso', models.CharField(db_column='claveAcceso', max_length=255, unique=True)),
                ('numautorizacion', models.CharField(db_column='numAutorizacion', max_length=255)),
                ('dirxml', models.CharField(db_column='dirXML', max_length=255)),
                ('dirpdf', models.CharField(db_column='dirPDF', max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('mensaje', models.CharField(max_length=255)),
                ('informacionadicional', models.CharField(db_column='informacionAdicional', max_length=255)),
            ],
            options={
                'db_table': 'comprobante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('razonsocial', models.TextField(db_column='razonSocial')),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodocumento', models.CharField(db_column='noDocumento', max_length=255)),
                ('claveacceso', models.CharField(db_column='claveAcceso', max_length=255, unique=True)),
                ('tiempo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('identificador', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'errores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('is_active', models.IntegerField()),
                ('createdat', models.DateTimeField(blank=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
