# Generated by Django 3.0.6 on 2020-07-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField()),
                ('cod_personal', models.CharField(max_length=14)),
                ('empleado', models.CharField(blank=True, max_length=101, null=True)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('cod_centro_costo', models.CharField(blank=True, max_length=10, null=True)),
                ('agencia', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('f_ingreso', models.CharField(blank=True, max_length=10, null=True)),
                ('f_egreso', models.CharField(blank=True, max_length=10, null=True)),
                ('f_reingreso', models.CharField(blank=True, max_length=10, null=True)),
                ('f_egreso2', models.CharField(blank=True, max_length=10, null=True)),
                ('ingreso3', models.CharField(blank=True, max_length=10, null=True)),
                ('egreso3', models.CharField(blank=True, max_length=10, null=True)),
                ('dias_laborados', models.FloatField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('e_mail_institucional', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_civil', models.CharField(max_length=50)),
                ('discapacidad', models.CharField(max_length=2)),
                ('empleo_juvenil', models.CharField(blank=True, max_length=1, null=True)),
                ('activo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'vt_personal',
                'managed': False,
            },
        ),
    ]
