# Generated by Django 3.0.6 on 2020-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_rhcomprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtRolesDescarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_personal', models.CharField(max_length=14)),
                ('empleado', models.CharField(blank=True, max_length=101, null=True)),
                ('agencia', models.CharField(max_length=50)),
                ('cod_comprobante', models.CharField(max_length=9)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('descargas', models.FloatField(blank=True, null=True)),
                ('last_descarga', models.DateField(blank=True, null=True)),
                ('usuario_descarga', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vt_roles_descarga',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rhcomprobante',
            options={'managed': False, 'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='vtpersonal',
            options={'managed': False, 'ordering': ['empleado']},
        ),
    ]
