# Generated by Django 3.0.6 on 2020-07-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20200716_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhPersonalTurnos',
            fields=[
                ('empresa', models.IntegerField()),
                ('cod_turno', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=20)),
                ('dias', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rh_personal_turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtTurnos',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('t1', models.CharField(blank=True, max_length=50, null=True)),
                ('t2', models.CharField(blank=True, max_length=50, null=True)),
                ('t3', models.CharField(blank=True, max_length=50, null=True)),
                ('t4', models.CharField(blank=True, max_length=50, null=True)),
                ('t5', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'vt_turnos',
                'managed': False,
            },
        ),
    ]
