# Generated by Django 3.0.6 on 2020-07-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20200716_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhPersonalTurnos',
            fields=[
                ('cod_persona', models.ForeignKey(db_column='cod_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personal.RhPersonal')),
                ('cod_turno', models.CharField(max_length=6)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rh_personal_turnos',
                'managed': False,
            },
        ),
    ]
