# Generated by Django 3.0.6 on 2020-10-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_rhpersonalturnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtUsuarioOracle',
            fields=[
                ('empresa', models.IntegerField()),
                ('cod_personal', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_cargo', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('e_mail_institucional', models.CharField(blank=True, max_length=50, null=True)),
                ('reingreso', models.CharField(blank=True, max_length=1, null=True)),
                ('usuario_oracle', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'vt_usuario_oracle',
                'managed': False,
            },
        ),
    ]
