# Generated by Django 3.0.6 on 2020-12-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_vtusuariooracle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tgagencia',
            options={'managed': False, 'ordering': ['nombre']},
        ),
    ]
