# Generated by Django 3.1.5 on 2021-01-18 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_rhdepartamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhPersonalD',
            fields=[
                ('cod_personal', models.ForeignKey(db_column='cod_personal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personal.rhpersonal')),
                ('cod_agencia', models.IntegerField()),
                ('ingreso_por', models.CharField(max_length=40)),
                ('reemplazode', models.CharField(blank=True, max_length=14, null=True)),
                ('cod_cargo', models.IntegerField()),
                ('descripcion_cargo', models.CharField(max_length=200)),
                ('fcargo_desde', models.DateField()),
                ('fcargo_hasta', models.DateField(blank=True, null=True)),
                ('f_ingreso', models.DateField()),
                ('f_egreso', models.DateField(blank=True, null=True)),
                ('registro_actual', models.CharField(max_length=3)),
                ('secuencia', models.IntegerField()),
                ('usuario_modifica', models.CharField(max_length=30)),
                ('motivo_salida', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_aud', models.DateField()),
            ],
            options={
                'db_table': 'rh_personal_d',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vtpersonal',
            options={'managed': False, 'ordering': ['agencia', 'empleado']},
        ),
    ]
