# Generated by Django 3.1.5 on 2021-01-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20210118_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhPersonalInstruccion',
            fields=[
                ('empresa', models.IntegerField()),
                ('cod_personal', models.ForeignKey(db_column='cod_personal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personal.rhpersonal')),
                ('cod_tipo_persona', models.CharField(max_length=3)),
                ('nivel_instruccion', models.CharField(max_length=20)),
                ('institucion', models.CharField(blank=True, max_length=40, null=True)),
                ('observacion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'RH_PERSONAL_INSTRUCCION',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rhpersonald',
            options={'managed': False, 'ordering': ['secuencia']},
        ),
    ]
