# Generated by Django 3.0.6 on 2020-07-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StProformaCabeceraTmp',
        ),
        migrations.DeleteModel(
            name='StProformaDetalleTmp',
        ),
    ]
