# Generated by Django 3.0.6 on 2020-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_bodegamassline'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtProductoDetalle',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('secuencia', models.FloatField()),
                ('caracteristicas', models.CharField(max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=4000, null=True)),
                ('nombre', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'vt_st_producto_detalle',
                'managed': False,
            },
        ),
    ]
