# Generated by Django 3.0.6 on 2020-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_vtcaracteristicasprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='StReservaProducto',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=2)),
                ('cod_comprobante', models.CharField(max_length=9)),
                ('fecha_registro', models.DateField()),
                ('usuario', models.CharField(max_length=15)),
                ('cod_producto', models.CharField(max_length=40)),
                ('numero_serie', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=40)),
                ('camvcpn', models.CharField(max_length=40)),
                ('origen', models.CharField(max_length=40)),
                ('anio', models.FloatField()),
                ('modelo', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=15)),
                ('aprobador_por', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('es_anulado', models.CharField(max_length=1)),
                ('fechaentrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=30)),
                ('cod_agencia', models.IntegerField()),
            ],
            options={
                'db_table': 'st_reserva_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtComprobanteWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField()),
                ('agencia', models.CharField(max_length=50)),
                ('cod_comprobante', models.CharField(max_length=9)),
                ('comprobante_sri', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_persona', models.CharField(max_length=14)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nombre_persona', models.CharField(blank=True, max_length=80, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'vt_comprobante_web',
                'managed': False,
            },
        ),
    ]
