# Generated by Django 3.0.6 on 2020-08-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_streservaproducto_vtcomprobanteweb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VtComprobanteWeb',
        ),
    ]
