# Generated by Django 3.0.6 on 2020-08-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_delete_vtcomprobanteweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtReservaBv',
            fields=[
                ('cod_comprobante', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cod_agencia', models.IntegerField()),
                ('agencia', models.CharField(max_length=50)),
                ('cod_producto', models.CharField(max_length=40)),
                ('cod_producto_proveedor', models.CharField(max_length=80)),
                ('numero_serie', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=40)),
                ('camvcpn', models.CharField(max_length=40)),
                ('anio', models.FloatField()),
                ('origen', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=15)),
                ('aprobador_por', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'vt_reserva_bv',
                'managed': False,
            },
        ),
    ]
