# Generated by Django 3.0.6 on 2020-08-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_vtreservabv'),
    ]

    operations = [
        migrations.CreateModel(
            name='vt_producto_web2',
            fields=[
                ('linea', models.CharField(max_length=50)),
                ('sublinea', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('segmento', models.CharField(max_length=50)),
                ('subsegmento', models.CharField(max_length=50)),
                ('cod_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vt_producto_web',
                'managed': False,
            },
        ),
    ]
