# Generated by Django 3.0.6 on 2020-09-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_vt_producto_web2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vtreservabv',
            table='vt_reserva_bodega',
        ),
    ]
