# Generated by Django 3.0.6 on 2020-09-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20200909_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='StProductoDetalleAuvi',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('secuencia', models.FloatField()),
                ('caracteristicas', models.CharField(max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'st_producto_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StProductoSerieAuvi',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_interno', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('bodegav', models.CharField(max_length=10)),
                ('cod_prod_bod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vt_producto_serie_web',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vt_producto_web_auvi',
            fields=[
                ('linea', models.CharField(max_length=50)),
                ('sublinea', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('segmento', models.CharField(max_length=50)),
                ('subsegmento', models.CharField(max_length=50)),
                ('cod_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('grupo', models.CharField(max_length=200)),
                ('bodegav', models.CharField(max_length=10)),
                ('cod_prod_bod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vt_producto_web_auvi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtListaPrecioAuvi',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vt_lista_precio',
                'managed': False,
            },
        ),
    ]
