# Generated by Django 3.0.6 on 2020-12-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_tmpimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='StInventarioObservacion',
            fields=[
                ('empresa', models.FloatField(primary_key=True, serialize=False)),
                ('secuencia', models.FloatField()),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'st_inventario_observacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StInventarioResultado',
            fields=[
                ('empresa', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=3)),
                ('cod_comprobante', models.CharField(max_length=9)),
                ('fecha', models.DateField()),
                ('cod_agencia', models.FloatField()),
                ('cod_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('cerrado', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_aud', models.DateField(blank=True, null=True)),
                ('usuario_aud', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'st_inventario_resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtReporteInventarioFinal',
            fields=[
                ('tipo', models.CharField(blank=True, max_length=4, null=True)),
                ('codigo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('tiene_devolucion', models.FloatField(blank=True, null=True)),
                ('motor', models.CharField(max_length=30)),
                ('chasis', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('total', models.CharField(blank=True, max_length=1, null=True)),
                ('agencia', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('dias', models.CharField(blank=True, max_length=7, null=True)),
                ('empresa', models.IntegerField()),
                ('cod_agencia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vt_reporte_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StInventarioResultadoD',
            fields=[
                ('empresa', models.OneToOneField(db_column='empresa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='emp_inv_res', serialize=False, to='inventario.StInventarioResultado')),
                ('secuencia', models.FloatField()),
                ('cod_producto', models.CharField(max_length=50)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('sobrante', models.CharField(max_length=1)),
                ('ingreso_manual_serie', models.CharField(max_length=1)),
                ('categoria', models.CharField(blank=True, max_length=10, null=True)),
                ('observacion1', models.CharField(max_length=100)),
                ('observacion2', models.CharField(blank=True, max_length=1000, null=True)),
                ('detalle', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_detalle', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'st_inventario_resultado_d',
                'managed': False,
            },
        ),
    ]
