# Generated by Django 3.0.6 on 2020-12-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('cod_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('empresa', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descuento_promocion', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
    ]
