# Generated by Django 3.0.6 on 2020-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtReporteInvAuvi',
            fields=[
                ('tipo', models.CharField(blank=True, max_length=4, null=True)),
                ('codigo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('cod_categoria', models.IntegerField()),
                ('tiene_devolucion', models.IntegerField(blank=True, null=True)),
                ('motor', models.CharField(max_length=30)),
                ('chasis', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('total', models.CharField(blank=True, max_length=1, null=True)),
                ('agencia', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('dias', models.CharField(blank=True, max_length=7, null=True)),
                ('empresa', models.IntegerField()),
                ('cod_agencia', models.IntegerField(blank=True, null=True)),
                ('invgrabado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vt_reporte_inv_auvi',
                'ordering': ['producto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtReporteRepuestos',
            fields=[
                ('tipo', models.CharField(blank=True, max_length=4, null=True)),
                ('codigo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('cod_categoria', models.CharField(max_length=200)),
                ('tiene_devolucion', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('dias', models.CharField(blank=True, max_length=1, null=True)),
                ('empresa', models.IntegerField()),
                ('cod_agencia', models.IntegerField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('invgrabado', models.IntegerField()),
            ],
            options={
                'db_table': 'vt_reporte_repuestos',
                'ordering': ['producto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtResultadoAudAuvi',
            fields=[
                ('cod_agencia', models.IntegerField(blank=True, null=True, primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=50)),
                ('total_prod', models.FloatField(blank=True, null=True)),
                ('registrados', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vt_resultado_aud_auvi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtResultadoAudMoto',
            fields=[
                ('cod_agencia', models.IntegerField(blank=True, null=True, primary_key=True, serialize=False)),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('total_prod', models.FloatField(blank=True, null=True)),
                ('registrados', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vt_resultado_aud_moto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtResultadoAudRep',
            fields=[
                ('cod_agencia', models.IntegerField(blank=True, null=True, primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=50)),
                ('total_prod', models.FloatField(blank=True, null=True)),
                ('registrados', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vt_resultado_aud_rep',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vtreporteinventariofinal',
            options={'managed': False, 'ordering': ['producto']},
        ),
    ]
