# Generated by Django 3.0.6 on 2020-12-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20201216_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtProdSerie',
            fields=[
                ('empresa', models.IntegerField()),
                ('cod_producto', models.CharField(max_length=40)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('serie', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('chasis', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'vt_prod_serie',
                'managed': False,
            },
        ),
    ]
