# Generated by Django 3.0.6 on 2020-12-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_vtprodserie'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtReporteAuditoriaGeneral',
            fields=[
                ('empresa', models.FloatField()),
                ('tipo_comprobante', models.CharField(max_length=3)),
                ('cod_comprobante', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cod_agencia', models.FloatField()),
                ('cod_producto', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=200)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('chasis', models.CharField(blank=True, max_length=20, null=True)),
                ('sobrante', models.CharField(max_length=1)),
                ('faltante', models.CharField(blank=True, max_length=1, null=True)),
                ('ingreso_manual_serie', models.CharField(max_length=1)),
                ('categoria', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria2', models.CharField(blank=True, max_length=46, null=True)),
                ('cantidad', models.FloatField()),
                ('estado_m', models.CharField(blank=True, max_length=500, null=True)),
                ('kit_m', models.CharField(blank=True, max_length=500, null=True)),
                ('observacion1', models.CharField(blank=True, max_length=500, null=True)),
                ('observacion2', models.CharField(blank=True, max_length=500, null=True)),
                ('rayon_r', models.CharField(blank=True, max_length=500, null=True)),
                ('transferencia_r', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad_reg_r', models.CharField(blank=True, max_length=500, null=True)),
                ('desperfecto_a', models.CharField(blank=True, max_length=500, null=True)),
                ('promocional_a', models.CharField(blank=True, max_length=500, null=True)),
                ('garantia_a', models.CharField(blank=True, max_length=500, null=True)),
                ('porrecibir_a', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'vt_reporte_auditoria_general',
                'ordering': ['-sobrante'],
                'managed': False,
            },
        ),
    ]
