# Generated by Django 3.1.5 on 2021-02-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_vtreporteauditoriageneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='StProdPackingList',
            fields=[
                ('cod_chasis', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cod_motor', models.CharField(max_length=30)),
                ('empresa', models.IntegerField()),
                ('fecha', models.DateField()),
                ('es_disponible', models.BooleanField(blank=True, null=True)),
                ('es_anulado', models.BooleanField(blank=True, null=True)),
                ('adicionado_por', models.CharField(max_length=30)),
                ('fecha_adicion', models.DateField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('eliminado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_elimiacion', models.DateField(blank=True, null=True)),
                ('camvcpn', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('marca', models.CharField(blank=True, max_length=30, null=True)),
                ('cilindraje', models.IntegerField()),
                ('pasajeros', models.IntegerField()),
                ('origen', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('tonelaje', models.CharField(max_length=5)),
                ('ejes', models.CharField(max_length=3)),
                ('ruedas', models.CharField(max_length=3)),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('combustible', models.CharField(blank=True, max_length=10, null=True)),
                ('color2', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ST_PROD_PACKING_LIST',
                'managed': False,
            },
        ),
    ]
