# Generated by Django 3.0.6 on 2020-07-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cod_personal',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
