# Generated by Django 3.0.6 on 2020-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_cod_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_oracle',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
