# Generated by Django 3.0.6 on 2020-10-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_user_oracle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_user_oracle',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
