# Generated by Django 3.0.6 on 2020-05-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('cod_marca', models.IntegerField()),
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descuento_promocion', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_unidad', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'unidad',
                'managed': False,
            },
        ),
    ]
