# Generated by Django 3.0.6 on 2020-12-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201207_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarmenu',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarmenu',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='sidebarMenuDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('id_menuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.sidebarMenu', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'MenuDet',
                'ordering': ['id'],
                'unique_together': {('id_menuc', 'nombre', 'nivel')},
            },
        ),
    ]
