# Generated by Django 3.0.6 on 2020-12-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201207_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmenu',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sidebarmenudet',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
