# Generated by Django 3.0.6 on 2020-12-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20201207_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebarmenudet',
            old_name='nivel',
            new_name='parent_id',
        ),
        migrations.AlterUniqueTogether(
            name='sidebarmenudet',
            unique_together={('id_menuc', 'nombre', 'parent_id')},
        ),
    ]
