# Generated by Django 3.0.6 on 2020-12-08 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20201207_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarmenudet',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.sidebarMenuDet'),
        ),
        migrations.AlterUniqueTogether(
            name='sidebarmenudet',
            unique_together={('id_menuc', 'id', 'parent_id')},
        ),
    ]
