# Generated by Django 3.0.6 on 2020-12-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20201207_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarmenudet',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
    ]
