# Generated by Django 3.0.6 on 2020-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20201208_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarmenudet',
            name='url',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
