# Generated by Django 3.0.6 on 2021-01-07 19:31

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20201208_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebarmenudet',
            options={'ordering': ['id_menuc__nombre', django.db.models.functions.comparison.Coalesce('parent_id_id', 'id'), 'descripcion'], 'verbose_name': 'MenuDet'},
        ),
        migrations.AlterField(
            model_name='sidebarmenudet',
            name='descripcion',
            field=models.CharField(blank=True, choices=[('Nivel 1', 'Nivel 1'), ('Nivel 1', 'Nivel 1')], max_length=100, null=True),
        ),
    ]
