# Generated by Django 3.0.6 on 2021-01-12 20:32

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20210107_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebarmenudet',
            options={'ordering': ['id_menuc__nombre', django.db.models.functions.comparison.Coalesce('parent_id_id', 'id'), 'descripcion', 'nombre'], 'verbose_name': 'MenuDet'},
        ),
        migrations.AlterField(
            model_name='sidebarmenudet',
            name='descripcion',
            field=models.CharField(choices=[('Menu Nivel 1', 'Menu Nivel 1'), ('Menu Nivel 2', 'Menu Nivel 2')], default='Menu Nivel 1', max_length=100),
            preserve_default=False,
        ),
    ]
