# Generated by Django 3.0.6 on 2020-05-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProducto', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StProductoDetalle',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('secuencia', models.FloatField()),
                ('caracteristicas', models.CharField(max_length=50)),
                ('detalle', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'st_producto_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vt_producto_web',
            fields=[
                ('linea', models.CharField(max_length=50)),
                ('sublinea', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('segmento', models.CharField(max_length=50)),
                ('subsegmento', models.CharField(max_length=50)),
                ('cod_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vt_producto_web',
                'managed': False,
            },
        ),
    ]
