# Generated by Django 3.0.6 on 2020-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebProducto', '0003_stproductodetalle_vt_producto_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='StProductoSerie',
            fields=[
                ('empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_interno', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'vt_producto_serie_web',
                'managed': False,
            },
        ),
    ]
