# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Comprobante(models.Model):
    empresa = models.ForeignKey('Persona', models.DO_NOTHING, db_column='empresa')
    tipo_comprobante = models.CharField(max_length=2)
    cod_comprobante = models.CharField(primary_key=True, max_length=9)
    cod_tipo_persona = models.ForeignKey('Persona', models.DO_NOTHING, db_column='cod_tipo_persona')
    cod_persona = models.ForeignKey('Persona', models.DO_NOTHING, db_column='cod_persona')
    fecha = models.DateField()
    pedido = models.CharField(max_length=13, blank=True, null=True)
    iva = models.DecimalField(max_digits=14, decimal_places=2)
    valor = models.DecimalField(max_digits=14, decimal_places=2)
    financiamiento = models.DecimalField(max_digits=14, decimal_places=2)
    otros = models.DecimalField(max_digits=14, decimal_places=2)
    descuento = models.DecimalField(max_digits=14, decimal_places=2)
    tipo_iva = models.CharField(max_length=1, blank=True, null=True)
    c_tipo_combrobante = models.CharField(max_length=2, blank=True, null=True)
    c_comprobante = models.CharField(max_length=9, blank=True, null=True)
    cod_liquidacion = models.ForeignKey('Liquidacion', models.DO_NOTHING, db_column='cod_liquidacion')
    useridc = models.CharField(max_length=3)
    factura_manual = models.CharField(max_length=9)
    anulado = models.CharField(max_length=1, blank=True, null=True)
    guia = models.CharField(max_length=9, blank=True, null=True)
    estado_grabado = models.CharField(max_length=1, blank=True, null=True)
    estado_contabilizado = models.CharField(max_length=1, blank=True, null=True)
    nombre_persona = models.CharField(max_length=80, blank=True, null=True)
    certificado = models.CharField(max_length=8, blank=True, null=True)
    secuen_certificado = models.ForeignKey('StTipoDevolucionAnticipo', models.DO_NOTHING, db_column='secuen_certificado', blank=True, null=True)
    orden_compra = models.CharField(max_length=9, blank=True, null=True)
    transportador = models.CharField(max_length=30, blank=True, null=True)
    placa = models.CharField(max_length=7, blank=True, null=True)
    observaciones = models.CharField(max_length=2000, blank=True, null=True)
    entrada = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    ice = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    cod_agente = models.CharField(max_length=14, blank=True, null=True)
    cod_divisa = models.CharField(max_length=20)
    valor_divisa = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    cancelada = models.CharField(max_length=1, blank=True, null=True)
    saldo = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    cod_agencia = models.IntegerField()
    forma_pago = models.CharField(max_length=3, blank=True, null=True)
    cotizacion = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    tipo_comprobante_r = models.CharField(max_length=2, blank=True, null=True)
    cod_comprobante_r = models.CharField(max_length=9, blank=True, null=True)
    transferencia = models.CharField(max_length=1, blank=True, null=True)
    aa_cliente = models.IntegerField(blank=True, null=True)
    codigo_cliente = models.CharField(max_length=14, blank=True, null=True)
    estado_comision = models.CharField(max_length=1, blank=True, null=True)
    cod_periodo_comision = models.ForeignKey('StPeriodoComision', models.DO_NOTHING, db_column='cod_periodo_comision', blank=True, null=True)
    linea_contabilidad = models.IntegerField(blank=True, null=True)
    tipo_comprobante_pr = models.ForeignKey('Proforma', models.DO_NOTHING, db_column='tipo_comprobante_pr', blank=True, null=True)
    cod_comprobante_pr = models.ForeignKey('Proforma', models.DO_NOTHING, db_column='cod_comprobante_pr', blank=True, null=True)
    cod_tipo_persona_gar = models.CharField(max_length=3, blank=True, null=True)
    cod_persona_gar = models.CharField(max_length=14, blank=True, null=True)
    numero_pagos = models.IntegerField()
    cuotas_gratis = models.DecimalField(max_digits=4, decimal_places=2)
    dias_atrazo = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    devolucion_otros = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    valor_alterno = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    descuento_promocion = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    cod_bodega_ingreso = models.ForeignKey('SubBodega', models.DO_NOTHING, db_column='cod_bodega_ingreso', blank=True, null=True)
    cod_subbodega_ingreso = models.ForeignKey('SubBodega', models.DO_NOTHING, db_column='cod_subbodega_ingreso', blank=True, null=True)
    cod_bodega_egreso = models.ForeignKey('SubBodega', models.DO_NOTHING, db_column='cod_bodega_egreso', blank=True, null=True)
    cod_subbodega_egreso = models.ForeignKey('SubBodega', models.DO_NOTHING, db_column='cod_subbodega_egreso', blank=True, null=True)
    cod_tarjeta = models.ForeignKey('StTarjetaCredito', models.DO_NOTHING, db_column='cod_tarjeta', blank=True, null=True)
    num_tarjeta = models.CharField(max_length=30, blank=True, null=True)
    num_recap = models.CharField(max_length=15, blank=True, null=True)
    num_voucher = models.CharField(max_length=15, blank=True, null=True)
    num_autorizacion = models.CharField(max_length=15, blank=True, null=True)
    cod_politica = models.ForeignKey('StPoliticaCredito', models.DO_NOTHING, db_column='cod_politica', blank=True, null=True)
    tipo_comprobante_pedido = models.CharField(max_length=2, blank=True, null=True)
    cod_comprobante_pedido = models.CharField(max_length=9, blank=True, null=True)
    fecha_ingreso = models.DateField(blank=True, null=True)
    rebate = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    base_imponible = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    base_excenta = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    cod_caja = models.IntegerField(blank=True, null=True)
    fecha_vencimiento1 = models.DateField(blank=True, null=True)
    por_interes = models.DecimalField(max_digits=7, decimal_places=4, blank=True, null=True)
    aud_fecha = models.DateField(blank=True, null=True)
    aud_usuario = models.CharField(max_length=30, blank=True, null=True)
    aud_terminal = models.CharField(max_length=50, blank=True, null=True)
    cod_tipo_persona_aprob = models.ForeignKey('Persona', models.DO_NOTHING, db_column='cod_tipo_persona_aprob', blank=True, null=True)
    cod_persona_aprob = models.ForeignKey('Persona', models.DO_NOTHING, db_column='cod_persona_aprob', blank=True, null=True)
    cod_tipo_persona_verif = models.ForeignKey('Persona', models.DO_NOTHING, db_column='cod_tipo_persona_verif', blank=True, null=True)
    cod_persona_verif = models.ForeignKey('Persona', models.DO_NOTHING, db_column='cod_persona_verif', blank=True, null=True)
    interes = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    compensacion_solidaria = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comprobante'
        unique_together = (('cod_comprobante', 'tipo_comprobante', 'empresa'),)
